# Generated by Django 5.1.3 on 2025-02-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("satellite", "Satellite"),
                            ("sensor", "Sensor"),
                            ("mission", "Mission"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("planned", "Planned"),
                        ],
                        max_length=50,
                    ),
                ),
                ("launch_date", models.DateField(blank=True, null=True)),
                (
                    "image_url",
                    models.URLField(default="https://via.placeholder.com/300"),
                ),
            ],
        ),
    ]
