# Generated by Django 5.1.3 on 2025-02-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nesis_app", "0002_crmuser_remove_asset_image_url_asset_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="image",
            field=models.ImageField(default="default_asset.jpg", upload_to="assets/"),
        ),
    ]
